<?php

/**
 * Implementing hook_permission 
 */
function sports_permission(){
  return array(
      'coach' => array(
          'title' => 'Coach',
          'description' => 'Coach administration',
      ),
  );
}

function sports_menu() {
  $items['stopwatch'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sports_stopwatch_form'),
    'access arguments' => array('access content'), 
    'file' => 'includes/sports.callbacks.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/sports'] = array(
    'title' => t('Sports settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sports_general_settings'),
    'access arguments' => array('coach'),
    'file' => 'includes/sports.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
/**
 * Implements hook_preprocess_page
 * @param string $vars
 */
function sports_preprocess_page(&$vars){
  if(arg(0) == 'stopwatch'){
//    $vars['theme_hook_suggestions'][0] = 'page__content_only';
  }
}

