<?php

/**
 * Implementing hook_permission 
 */
function sports_permission(){
  return array(
      'coach' => array(
          'title' => 'Coach',
          'description' => 'Coach administration',
      ),
  );
}

function sports_menu() {
  $items['stopwatch'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sports_stopwatch_form'),
    'access arguments' => array('access content'), 
    'file' => 'includes/sports.callbacks.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function sports_preprocess_page(&$vars){
  if(arg(0) == 'stopwatch'){
    $vars['theme_hook_suggestions'][0] = 'page__content_only';
  }
}