<?php
/*
 * Implementing hook_permission
 */
function sports_permission(){
 return array(
    'administer sports' => array(
      'title' => t('Administer sports'), 
      'description' => t('Perform administration tasks for sports module.'),
    ),
  ); 
}
/*
 * Implementing hook_menu
 */
function sports_menu(){
  $items['load'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sports_load_form'),
    'access arguments' => array('administer sports'),
    'file' => 'includes/sports.callbacks.inc',
    'type' => MENU_CALLBACK,
  );
  $items['stopwatch'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sports_stopwatch_form'),
    'access arguments' => array('administer sports'),
    'file' => 'includes/sports.callbacks.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}
